-- DROP the tables and constraints
DROP TABLE IF EXISTS pollers;
DROP TABLE IF EXISTS errors;
DROP TABLE IF EXISTS operators;


-- create the pollers table, it depends on no other
CREATE TABLE pollers (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  poller_name VARCHAR NOT NULL,
  description VARCHAR,
  UNIQUE (poller_name)
);

-- create the operators table with the foreign key
CREATE TABLE operators (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  username TEXT NOT NULL,
  UNIQUE (username)
);

-- create the errors table with the foreign key
CREATE TABLE errors (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  operator INTEGER REFERENCES operators(id) ON DELETE CASCADE,
  error_description VARCHAR NOT NULL,
  poller_id INTEGER REFERENCES pollers(id) ON DELETE CASCADE,
  posted TIMESTAMP DEFAULT NOW()
);